name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger this action on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Log in to Docker Hub using secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build and tag the Docker image
      run: |
        docker build -t bhanuu1903/todo-list-app .

    # Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push bhanuu1903/todo-list-app
