name: Django-docker-pipeline

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate  # Note the change here
          pip install --upgrade pip setuptools wheel  # Upgrade pip and dependencies
          pip install -r requirements.txt

      - name: Build Docker Image
        run: |
          docker build -t bhanuu1903/todo-app:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push to Docker Hub
        run: docker push bhanuu1903/todo-app:latest
